version: '3.8'

services:
  app:
    container_name: app
    build:
      dockerfile: ./infra/Dockerfile.dev
      context: ../
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge